name: Flask CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
          uses: actions/setup-python@v3.11.3
          with: 
           python-version: 3.11.3
           

      - name: Install dependencies
        run: |
            echo building

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v3.11.3
        with:
          python-version: 3.11.3

      - name: Run tests
        run: |
          python3 --version
          echo testing

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
          
      - name: Deploy to Ec2 Instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |  
            cd /home/ubuntu
            sudo apt update
            cd FlaskChess
            pip install -r requirements.txt
            python 3 flask_app.py
            gunicorn --bind 0.0.0.0:5000 wsgi:app
            sudo cp gunicorn.service /etc/systemd/system
            sudo systemctl daemon-reload
            sudo systemctl start gunicorn


